apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_DATABASE: U3FsMDE=             # Base64 encoded "Sql01"
  MYSQL_USER: dXNlcjE=                 # Base64 encoded "user1"
  MYSQL_PASSWORD: cGFzc3dvcmQ=         # Base64 encoded "password"
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQxMjM= # Base64 encoded "password123"
